import { Router, Request, Response } from 'express';
import Groq from 'groq-sdk';
import dotenv from 'dotenv';
import PDFDocument from 'pdfkit';

dotenv.config();

const router = Router();
const groq = process.env.GROQ_API_KEY ? new Groq({ apiKey: process.env.GROQ_API_KEY }) : null;

const PROMPTS: Record<string, (topic: string, grade: string) => string> = {
  lesson: (topic, grade) => `Create a detailed 5-day lesson plan for "${topic}" for ${grade} students. Format it clearly with Day 1 through Day 5. Under each day, please provide a clear list of specific "Tasks to Do" and "Learning Activities" formatted with bullet points (using '•') so they can be easily tracked as a checklist.`,
  comments: (topic, grade) => `Generate 3 grade book progress report comments for "${topic}" for ${grade} students. Include one for Excellent performance, one for Developing/Moderate, and one for Action Required. Under each comment, write 2-3 specific action items for the student/teacher, formatted as bullet points (using '•').`,
  rubric: (topic, grade) => `Create a detailed grading rubric for assessing "${topic}" for ${grade} students. Include 3 criteria with 4 performance levels each (Excellent, Good, Basic, Insufficient) and clear percentage weights. Format it with clear checklist-style items (using '•') for expectations.`,
};

// POST /api/toolkit/generate
router.post('/generate', async (req: Request, res: Response) => {
  try {
    const { tool, topic, grade } = req.body;

    if (!tool || !topic) {
      return res.status(400).json({ error: 'Tool and topic are required.' });
    }

    const promptFn = PROMPTS[tool];
    if (!promptFn) {
      return res.status(400).json({ error: 'Invalid tool type.' });
    }

    const userPrompt = promptFn(topic, grade || 'Grade 10');

    if (!groq) {
      // Fallback template when no Groq key
      const toolLabel = tool === 'lesson' ? 'Lesson Plan' : tool === 'comments' ? 'Grade Comments' : 'Rubric';
      return res.json({
        result: `📋 [AI Generated ${toolLabel}: ${topic} — ${grade}]\n${'─'.repeat(50)}\n\nThis outline provides a structured workflow for "${topic}" tailored for ${grade}.\n\nTasks & Objectives Checklist:\n• Step 1: Review the fundamental principles of ${topic} with the class.\n• Step 2: Conduct a 15-minute diagnostic quiz to assess baseline understanding.\n• Step 3: Distribute practice problems covering core applications.\n• Step 4: Map grade comments and review rubrics for term grading.\n• Step 5: Assign homework outline and record progress in class registry.`
      });
    }

    const completion = await groq.chat.completions.create({
      messages: [
        { role: 'system', content: 'You are a professional educator AI assistant. Generate clear, structured, educationally sound content for teachers. Use markdown-style formatting with clear headers.' },
        { role: 'user', content: userPrompt }
      ],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.7,
      max_tokens: 1024
    });

    const result = completion.choices[0]?.message?.content || 'No content generated.';
    return res.json({ result });
  } catch (error: any) {
    console.error('Toolkit generation error:', error);
    return res.status(500).json({ error: error.message || 'Generation failed' });
  }
});

// POST /api/toolkit/export-pdf
router.post('/export-pdf', async (req: Request, res: Response) => {
  try {
    const { tool, topic, grade, aiResponse } = req.body;

    if (!aiResponse) {
      return res.status(400).json({ error: 'No content to export.' });
    }

    const toolLabel = tool === 'lesson' ? 'Lesson Plan' : tool === 'comments' ? 'Grade Comments' : 'Rubric';
    
    // Create PDFkit document
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 }
    });

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=VedaAI-${tool}-${topic.replace(/\s+/g, '-')}.pdf`);

    doc.pipe(res);

    // --- HEADER ---
    doc.font('Helvetica-Bold').fontSize(18).fillColor('#ea580c').text('VEDA AI ACADEMY', { align: 'center' });
    doc.fontSize(10).fillColor('#4b5563').text("TEACHER'S PROFESSIONAL TOOLKIT", { align: 'center' });
    
    // Horizontal divider
    doc.moveDown(0.5);
    doc.strokeColor('#e5e7eb').lineWidth(1.5).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.8);

    // --- TITLE & METADATA ---
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#1f2937').text(`${toolLabel.toUpperCase()}: ${topic.toUpperCase()}`);
    doc.font('Helvetica-Oblique').fontSize(10).fillColor('#6b7280').text(`Target Grade: ${grade || 'Grade 10'}  |  Generated by VedaAI`);
    
    doc.moveDown(1.2);
    doc.strokeColor('#ea580c').lineWidth(1.5).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1.5);

    // --- PARSE AND DRAW CONTENT ---
    const lines = aiResponse.split('\n');

    lines.forEach((line: string) => {
      const trimmed = line.trim();
      if (trimmed === '') {
        doc.moveDown(0.5);
        return;
      }

      if (trimmed.includes('─') || trimmed.includes('=')) {
        doc.moveDown(0.3);
        doc.strokeColor('#e5e7eb').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown(0.5);
        return;
      }

      const cleanLine = trimmed.replace(/^[•\-*]\s*/, '').trim();

      // Check header patterns (like Day X, Tasks to Do, etc.)
      const isHeaderPattern = cleanLine.startsWith('#') || 
                              cleanLine.match(/^(Day \d+|Day [A-Za-z]+|Tasks to Do|Objectives|Activity|Learning Activities|Criteria \d+):/i) ||
                              (cleanLine.length > 2 && cleanLine === cleanLine.toUpperCase() && !cleanLine.includes('─') && !cleanLine.includes('='));

      if (isHeaderPattern) {
        const cleanHeader = cleanLine.replace(/^#+\s*/, '');
        // Check for page overflow
        if (doc.y > 700) {
          doc.addPage();
        }
        doc.moveDown(0.8);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#ea580c').text(cleanHeader);
        doc.moveDown(0.4);
        return;
      }

      const isBullet = trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*');

      if (isBullet) {
        // Check for page overflow
        if (doc.y > 720) {
          doc.addPage();
        }

        const currentY = doc.y;
        
        // Draw checkbox
        doc.strokeColor('#4b5563').lineWidth(1).rect(55, currentY + 1, 10, 10).stroke();
        
        // Draw text
        doc.font('Helvetica').fontSize(10).fillColor('#1f2937');
        doc.text(cleanLine, 75, currentY, { width: 470 });
        doc.moveDown(0.6);
        return;
      }

      // Normal text paragraph
      if (doc.y > 720) {
        doc.addPage();
      }
      doc.font('Helvetica').fontSize(10).fillColor('#374151');
      doc.text(trimmed, 50, doc.y, { width: 495 });
      doc.moveDown(0.6);
    });

    // --- FOOTER NOTE ---
    if (doc.y < 740) {
      doc.strokeColor('#e5e7eb').lineWidth(0.5).moveTo(50, 770).lineTo(545, 770).stroke();
      doc.font('Helvetica').fontSize(8).fillColor('#9ca3af').text('Powered by VedaAI Teacher\'s Toolkit', 50, 775, { align: 'center' });
    }

    doc.end();
  } catch (error: any) {
    console.error('Toolkit PDF generation error:', error);
    return res.status(500).json({ error: error.message || 'PDF export failed' });
  }
});

export default router;
